spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/templatedb
    username: template
    password: template
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
